version: "1"
services:
  # kafka:
  #   container_name: kafka
  #   image: "bitnami/kafka:latest"
  #   ports:
  #     - "9092:9092"
  #   networks:
  #     - gateway
  #   environment:
  #     - KAFKA_CFG_NODE_ID=0
  #     - KAFKA_CFG_PROCESS_ROLES=controller,broker
  #     - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
  #     - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
  #     - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
  #     - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"
    networks:
      - gateway
    restart: always

  kafka:
    image: wurstmeister/kafka:2.13-2.7.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - gateway
    restart: always

  # gateway:
  #   build: ./gateway
  #   ports:
  #     - "8080:8080"
  #   networks:
  #     - gateway
  #   restart: always
  #   depends_on:
  #     - loan-processing
  #     - notification-service
  #     - kafka

  loan-processing:
    container_name: loan-processing
    build: ./loan_processing_manager
    ports:
      - "3000:3000"
    networks:
      - gateway
    restart: always
    depends_on:
      - kafka

  commercial-service:
    container_name: commercial-service
    build: ./commercial_service
    ports:
      - "3001:3000"
    networks:
      - gateway
    restart: always
    depends_on:
      - kafka

  data-extraction:
    container_name: data-extraction
    build: ./data_extraction_service
    ports:
      - "3002:3000"
    networks:
      - gateway
    restart: always
    depends_on:
      - kafka

  risk_managment_service:
    container_name: risk_managment_service
    build: ./risk_managment_service
    ports:
      - "3003:3000"
    networks:
      - gateway
    restart: always
    depends_on:
      - kafka

  notification-service:
    container_name: notification-service
    build: ./notification_service
    ports:
      - "3004:3000"
    networks:
      - gateway
    restart: always
    depends_on:
      - kafka
networks:
  gateway:
    # driver: bridge
